services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interswitch-lms
    ports:
      - "3039:3000"
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge